from setuptools import setup

setup(
	name='social-box_server',
	version='1.0',
	packages=['venv.lib.python3.7.site-packages.bson', 'venv.lib.python3.7.site-packages.idna',
			  'venv.lib.python3.7.site-packages.maya', 'venv.lib.python3.7.site-packages.objc',
			  'venv.lib.python3.7.site-packages.past', 'venv.lib.python3.7.site-packages.past.tests',
			  'venv.lib.python3.7.site-packages.past.types', 'venv.lib.python3.7.site-packages.past.utils',
			  'venv.lib.python3.7.site-packages.past.builtins', 'venv.lib.python3.7.site-packages.past.translation',
			  'venv.lib.python3.7.site-packages.pint', 'venv.lib.python3.7.site-packages.pint.compat',
			  'venv.lib.python3.7.site-packages.pint.testsuite', 'venv.lib.python3.7.site-packages.pytz',
			  'venv.lib.python3.7.site-packages.AVKit', 'venv.lib.python3.7.site-packages.click',
			  'venv.lib.python3.7.site-packages.Cocoa', 'venv.lib.python3.7.site-packages.flask',
			  'venv.lib.python3.7.site-packages.flask.json', 'venv.lib.python3.7.site-packages.geopy',
			  'venv.lib.python3.7.site-packages.geopy.extra', 'venv.lib.python3.7.site-packages.geopy.geocoders',
			  'venv.lib.python3.7.site-packages.NetFS', 'venv.lib.python3.7.site-packages.QTKit',
			  'venv.lib.python3.7.site-packages.regex', 'venv.lib.python3.7.site-packages.regex.test',
			  'venv.lib.python3.7.site-packages.AppKit', 'venv.lib.python3.7.site-packages.CoreML',
			  'venv.lib.python3.7.site-packages.future', 'venv.lib.python3.7.site-packages.future.moves',
			  'venv.lib.python3.7.site-packages.future.moves.dbm', 'venv.lib.python3.7.site-packages.future.moves.html',
			  'venv.lib.python3.7.site-packages.future.moves.http',
			  'venv.lib.python3.7.site-packages.future.moves.test',
			  'venv.lib.python3.7.site-packages.future.moves.urllib',
			  'venv.lib.python3.7.site-packages.future.moves.xmlrpc',
			  'venv.lib.python3.7.site-packages.future.moves.tkinter', 'venv.lib.python3.7.site-packages.future.tests',
			  'venv.lib.python3.7.site-packages.future.types', 'venv.lib.python3.7.site-packages.future.utils',
			  'venv.lib.python3.7.site-packages.future.builtins', 'venv.lib.python3.7.site-packages.future.backports',
			  'venv.lib.python3.7.site-packages.future.backports.html',
			  'venv.lib.python3.7.site-packages.future.backports.http',
			  'venv.lib.python3.7.site-packages.future.backports.test',
			  'venv.lib.python3.7.site-packages.future.backports.email',
			  'venv.lib.python3.7.site-packages.future.backports.email.mime',
			  'venv.lib.python3.7.site-packages.future.backports.urllib',
			  'venv.lib.python3.7.site-packages.future.backports.xmlrpc',
			  'venv.lib.python3.7.site-packages.future.standard_library', 'venv.lib.python3.7.site-packages.gridfs',
			  'venv.lib.python3.7.site-packages.jinja2', 'venv.lib.python3.7.site-packages.MapKit',
			  'venv.lib.python3.7.site-packages.OSAKit', 'venv.lib.python3.7.site-packages.Photos',
			  'venv.lib.python3.7.site-packages.PubSub', 'venv.lib.python3.7.site-packages.Quartz',
			  'venv.lib.python3.7.site-packages.Quartz.PDFKit', 'venv.lib.python3.7.site-packages.Quartz.ImageIO',
			  'venv.lib.python3.7.site-packages.Quartz.ImageKit', 'venv.lib.python3.7.site-packages.Quartz.CoreVideo',
			  'venv.lib.python3.7.site-packages.Quartz.QuartzCore',
			  'venv.lib.python3.7.site-packages.Quartz.QuickLookUI',
			  'venv.lib.python3.7.site-packages.Quartz.CoreGraphics',
			  'venv.lib.python3.7.site-packages.Quartz.QuartzFilters',
			  'venv.lib.python3.7.site-packages.Quartz.QuartzComposer', 'venv.lib.python3.7.site-packages.Social',
			  'venv.lib.python3.7.site-packages.Vision', 'venv.lib.python3.7.site-packages.WebKit',
			  'venv.lib.python3.7.site-packages.certifi', 'venv.lib.python3.7.site-packages.chardet',
			  'venv.lib.python3.7.site-packages.chardet.cli', 'venv.lib.python3.7.site-packages.GameKit',
			  'venv.lib.python3.7.site-packages.Intents', 'venv.lib.python3.7.site-packages.ModelIO',
			  'venv.lib.python3.7.site-packages.Network', 'venv.lib.python3.7.site-packages.passlib',
			  'venv.lib.python3.7.site-packages.passlib.ext', 'venv.lib.python3.7.site-packages.passlib.ext.django',
			  'venv.lib.python3.7.site-packages.passlib.tests', 'venv.lib.python3.7.site-packages.passlib.utils',
			  'venv.lib.python3.7.site-packages.passlib.utils.compat',
			  'venv.lib.python3.7.site-packages.passlib.crypto',
			  'venv.lib.python3.7.site-packages.passlib.crypto.scrypt',
			  'venv.lib.python3.7.site-packages.passlib.crypto._blowfish',
			  'venv.lib.python3.7.site-packages.passlib.handlers', 'venv.lib.python3.7.site-packages.pymongo',
			  'venv.lib.python3.7.site-packages.ratelim', 'venv.lib.python3.7.site-packages.suntime',
			  'venv.lib.python3.7.site-packages.tzlocal', 'venv.lib.python3.7.site-packages.urllib3',
			  'venv.lib.python3.7.site-packages.urllib3.util', 'venv.lib.python3.7.site-packages.urllib3.contrib',
			  'venv.lib.python3.7.site-packages.urllib3.contrib._securetransport',
			  'venv.lib.python3.7.site-packages.urllib3.packages',
			  'venv.lib.python3.7.site-packages.urllib3.packages.backports',
			  'venv.lib.python3.7.site-packages.urllib3.packages.ssl_match_hostname',
			  'venv.lib.python3.7.site-packages.Accounts', 'venv.lib.python3.7.site-packages.CloudKit',
			  'venv.lib.python3.7.site-packages.Contacts', 'venv.lib.python3.7.site-packages.CoreData',
			  'venv.lib.python3.7.site-packages.CoreText', 'venv.lib.python3.7.site-packages.CoreWLAN',
			  'venv.lib.python3.7.site-packages.dateutil', 'venv.lib.python3.7.site-packages.dateutil.tz',
			  'venv.lib.python3.7.site-packages.dateutil.parser', 'venv.lib.python3.7.site-packages.dateutil.zoneinfo',
			  'venv.lib.python3.7.site-packages.EventKit', 'venv.lib.python3.7.site-packages.FSEvents',
			  'venv.lib.python3.7.site-packages.geocoder', 'venv.lib.python3.7.site-packages.humanize',
			  'venv.lib.python3.7.site-packages.keyboard', 'venv.lib.python3.7.site-packages.pendulum',
			  'venv.lib.python3.7.site-packages.pendulum.tz', 'venv.lib.python3.7.site-packages.pendulum.tz.data',
			  'venv.lib.python3.7.site-packages.pendulum.tz.zoneinfo',
			  'venv.lib.python3.7.site-packages.pendulum.utils', 'venv.lib.python3.7.site-packages.pendulum.mixins',
			  'venv.lib.python3.7.site-packages.pendulum.locales',
			  'venv.lib.python3.7.site-packages.pendulum.locales.da',
			  'venv.lib.python3.7.site-packages.pendulum.locales.de',
			  'venv.lib.python3.7.site-packages.pendulum.locales.en',
			  'venv.lib.python3.7.site-packages.pendulum.locales.es',
			  'venv.lib.python3.7.site-packages.pendulum.locales.fa',
			  'venv.lib.python3.7.site-packages.pendulum.locales.fo',
			  'venv.lib.python3.7.site-packages.pendulum.locales.fr',
			  'venv.lib.python3.7.site-packages.pendulum.locales.ko',
			  'venv.lib.python3.7.site-packages.pendulum.locales.lt',
			  'venv.lib.python3.7.site-packages.pendulum.locales.zh',
			  'venv.lib.python3.7.site-packages.pendulum.locales.pt_br',
			  'venv.lib.python3.7.site-packages.pendulum.parsing',
			  'venv.lib.python3.7.site-packages.pendulum.parsing.exceptions',
			  'venv.lib.python3.7.site-packages.pendulum.formatting',
			  'venv.lib.python3.7.site-packages.pendulum._extensions', 'venv.lib.python3.7.site-packages.PhotosUI',
			  'venv.lib.python3.7.site-packages.pytzdata', 'venv.lib.python3.7.site-packages.pytzdata.commands',
			  'venv.lib.python3.7.site-packages.requests', 'venv.lib.python3.7.site-packages.SceneKit',
			  'venv.lib.python3.7.site-packages.Security', 'venv.lib.python3.7.site-packages.snaptime',
			  'venv.lib.python3.7.site-packages.StoreKit', 'venv.lib.python3.7.site-packages.werkzeug',
			  'venv.lib.python3.7.site-packages.werkzeug.debug', 'venv.lib.python3.7.site-packages.werkzeug.contrib',
			  'venv.lib.python3.7.site-packages.werkzeug.wrappers',
			  'venv.lib.python3.7.site-packages.werkzeug.middleware', 'venv.lib.python3.7.site-packages.AdSupport',
			  'venv.lib.python3.7.site-packages.Automator', 'venv.lib.python3.7.site-packages.CFNetwork',
			  'venv.lib.python3.7.site-packages.ColorSync', 'venv.lib.python3.7.site-packages.CoreAudio',
			  'venv.lib.python3.7.site-packages.CoreMedia', 'venv.lib.python3.7.site-packages.IOSurface',
			  'venv.lib.python3.7.site-packages.PrintCore', 'venv.lib.python3.7.site-packages.SearchKit',
			  'venv.lib.python3.7.site-packages.SpriteKit', 'venv.lib.python3.7.site-packages.ContactsUI',
			  'venv.lib.python3.7.site-packages.dateparser', 'venv.lib.python3.7.site-packages.dateparser.data',
			  'venv.lib.python3.7.site-packages.dateparser.data.date_translation_data',
			  'venv.lib.python3.7.site-packages.dateparser.data.numeral_translation_data',
			  'venv.lib.python3.7.site-packages.dateparser.utils', 'venv.lib.python3.7.site-packages.dateparser.search',
			  'venv.lib.python3.7.site-packages.dateparser.calendars',
			  'venv.lib.python3.7.site-packages.dateparser.languages', 'venv.lib.python3.7.site-packages.FinderSync',
			  'venv.lib.python3.7.site-packages.Foundation', 'venv.lib.python3.7.site-packages.GameCenter',
			  'venv.lib.python3.7.site-packages.googlemaps', 'venv.lib.python3.7.site-packages.HIServices',
			  'venv.lib.python3.7.site-packages.markupsafe', 'venv.lib.python3.7.site-packages.AddressBook',
			  'venv.lib.python3.7.site-packages.CoreMediaIO', 'venv.lib.python3.7.site-packages.DVDPlayback',
			  'venv.lib.python3.7.site-packages.GameplayKit', 'venv.lib.python3.7.site-packages.libdispatch',
			  'venv.lib.python3.7.site-packages.libfuturize', 'venv.lib.python3.7.site-packages.libfuturize.fixes',
			  'venv.lib.python3.7.site-packages.MediaPlayer', 'venv.lib.python3.7.site-packages.ScreenSaver',
			  'venv.lib.python3.7.site-packages.AVFoundation', 'venv.lib.python3.7.site-packages.BusinessChat',
			  'venv.lib.python3.7.site-packages.CoreAudioKit', 'venv.lib.python3.7.site-packages.CoreLocation',
			  'venv.lib.python3.7.site-packages.CoreServices', 'venv.lib.python3.7.site-packages.CoreServices.Metadata',
			  'venv.lib.python3.7.site-packages.CoreServices.SearchKit',
			  'venv.lib.python3.7.site-packages.CoreServices.CarbonCore',
			  'venv.lib.python3.7.site-packages.CoreServices.LaunchServices',
			  'venv.lib.python3.7.site-packages.CoreServices.DictionaryServices',
			  'venv.lib.python3.7.site-packages.itsdangerous', 'venv.lib.python3.7.site-packages.MediaLibrary',
			  'venv.lib.python3.7.site-packages.MediaToolbox', 'venv.lib.python3.7.site-packages.SyncServices',
			  'venv.lib.python3.7.site-packages.VideoToolbox', 'venv.lib.python3.7.site-packages.CalendarStore',
			  'venv.lib.python3.7.site-packages.Collaboration', 'venv.lib.python3.7.site-packages.CoreBluetooth',
			  'venv.lib.python3.7.site-packages.CoreSpotlight', 'venv.lib.python3.7.site-packages.DiscRecording',
			  'venv.lib.python3.7.site-packages.flask_pymongo', 'venv.lib.python3.7.site-packages.flask_pymongo.tests',
			  'venv.lib.python3.7.site-packages.geographiclib', 'venv.lib.python3.7.site-packages.geographiclib.test',
			  'venv.lib.python3.7.site-packages.iTunesLibrary', 'venv.lib.python3.7.site-packages.libpasteurize',
			  'venv.lib.python3.7.site-packages.libpasteurize.fixes', 'venv.lib.python3.7.site-packages.OpenDirectory',
			  'venv.lib.python3.7.site-packages.AppleScriptKit', 'venv.lib.python3.7.site-packages.CoreFoundation',
			  'venv.lib.python3.7.site-packages.CryptoTokenKit', 'venv.lib.python3.7.site-packages.GameController',
			  'venv.lib.python3.7.site-packages.InputMethodKit', 'venv.lib.python3.7.site-packages.InstantMessage',
			  'venv.lib.python3.7.site-packages.JavaScriptCore', 'venv.lib.python3.7.site-packages.LaunchServices',
			  'venv.lib.python3.7.site-packages.SafariServices', 'venv.lib.python3.7.site-packages.AppleScriptObjC',
			  'venv.lib.python3.7.site-packages.CFOpenDirectory', 'venv.lib.python3.7.site-packages.dateparser_data',
			  'venv.lib.python3.7.site-packages.DiscRecordingUI', 'venv.lib.python3.7.site-packages.DiskArbitration',
			  'venv.lib.python3.7.site-packages.IMServicePlugIn', 'venv.lib.python3.7.site-packages.NaturalLanguage',
			  'venv.lib.python3.7.site-packages.PreferencePanes', 'venv.lib.python3.7.site-packages.ScriptingBridge',
			  'venv.lib.python3.7.site-packages.ImageCaptureCore', 'venv.lib.python3.7.site-packages.InstallerPlugins',
			  'venv.lib.python3.7.site-packages.NetworkExtension', 'venv.lib.python3.7.site-packages.ExceptionHandling',
			  'venv.lib.python3.7.site-packages.ExternalAccessory',
			  'venv.lib.python3.7.site-packages.SecurityInterface',
			  'venv.lib.python3.7.site-packages.ServiceManagement',
			  'venv.lib.python3.7.site-packages.UserNotifications',
			  'venv.lib.python3.7.site-packages.DictionaryServices',
			  'venv.lib.python3.7.site-packages.MediaAccessibility',
			  'venv.lib.python3.7.site-packages.NotificationCenter',
			  'venv.lib.python3.7.site-packages.SecurityFoundation',
			  'venv.lib.python3.7.site-packages.ApplicationServices',
			  'venv.lib.python3.7.site-packages.LocalAuthentication',
			  'venv.lib.python3.7.site-packages.pip-9.0.3-py3.7.egg.pip',
			  'venv.lib.python3.7.site-packages.pip-9.0.3-py3.7.egg.pip.req',
			  'venv.lib.python3.7.site-packages.pip-9.0.3-py3.7.egg.pip.vcs',
			  'venv.lib.python3.7.site-packages.pip-9.0.3-py3.7.egg.pip.utils',
			  'venv.lib.python3.7.site-packages.pip-9.0.3-py3.7.egg.pip.compat',
			  'venv.lib.python3.7.site-packages.pip-9.0.3-py3.7.egg.pip.models',
			  'venv.lib.python3.7.site-packages.pip-9.0.3-py3.7.egg.pip._vendor',
			  'venv.lib.python3.7.site-packages.pip-9.0.3-py3.7.egg.pip._vendor.idna',
			  'venv.lib.python3.7.site-packages.pip-9.0.3-py3.7.egg.pip._vendor.certifi',
			  'venv.lib.python3.7.site-packages.pip-9.0.3-py3.7.egg.pip._vendor.chardet',
			  'venv.lib.python3.7.site-packages.pip-9.0.3-py3.7.egg.pip._vendor.chardet.cli',
			  'venv.lib.python3.7.site-packages.pip-9.0.3-py3.7.egg.pip._vendor.distlib',
			  'venv.lib.python3.7.site-packages.pip-9.0.3-py3.7.egg.pip._vendor.distlib._backport',
			  'venv.lib.python3.7.site-packages.pip-9.0.3-py3.7.egg.pip._vendor.urllib3',
			  'venv.lib.python3.7.site-packages.pip-9.0.3-py3.7.egg.pip._vendor.urllib3.util',
			  'venv.lib.python3.7.site-packages.pip-9.0.3-py3.7.egg.pip._vendor.urllib3.contrib',
			  'venv.lib.python3.7.site-packages.pip-9.0.3-py3.7.egg.pip._vendor.urllib3.contrib._securetransport',
			  'venv.lib.python3.7.site-packages.pip-9.0.3-py3.7.egg.pip._vendor.urllib3.packages',
			  'venv.lib.python3.7.site-packages.pip-9.0.3-py3.7.egg.pip._vendor.urllib3.packages.backports',
			  'venv.lib.python3.7.site-packages.pip-9.0.3-py3.7.egg.pip._vendor.urllib3.packages.ssl_match_hostname',
			  'venv.lib.python3.7.site-packages.pip-9.0.3-py3.7.egg.pip._vendor.colorama',
			  'venv.lib.python3.7.site-packages.pip-9.0.3-py3.7.egg.pip._vendor.html5lib',
			  'venv.lib.python3.7.site-packages.pip-9.0.3-py3.7.egg.pip._vendor.html5lib._trie',
			  'venv.lib.python3.7.site-packages.pip-9.0.3-py3.7.egg.pip._vendor.html5lib.filters',
			  'venv.lib.python3.7.site-packages.pip-9.0.3-py3.7.egg.pip._vendor.html5lib.treewalkers',
			  'venv.lib.python3.7.site-packages.pip-9.0.3-py3.7.egg.pip._vendor.html5lib.treeadapters',
			  'venv.lib.python3.7.site-packages.pip-9.0.3-py3.7.egg.pip._vendor.html5lib.treebuilders',
			  'venv.lib.python3.7.site-packages.pip-9.0.3-py3.7.egg.pip._vendor.lockfile',
			  'venv.lib.python3.7.site-packages.pip-9.0.3-py3.7.egg.pip._vendor.progress',
			  'venv.lib.python3.7.site-packages.pip-9.0.3-py3.7.egg.pip._vendor.requests',
			  'venv.lib.python3.7.site-packages.pip-9.0.3-py3.7.egg.pip._vendor.packaging',
			  'venv.lib.python3.7.site-packages.pip-9.0.3-py3.7.egg.pip._vendor.cachecontrol',
			  'venv.lib.python3.7.site-packages.pip-9.0.3-py3.7.egg.pip._vendor.cachecontrol.caches',
			  'venv.lib.python3.7.site-packages.pip-9.0.3-py3.7.egg.pip._vendor.webencodings',
			  'venv.lib.python3.7.site-packages.pip-9.0.3-py3.7.egg.pip._vendor.pkg_resources',
			  'venv.lib.python3.7.site-packages.pip-9.0.3-py3.7.egg.pip.commands',
			  'venv.lib.python3.7.site-packages.pip-9.0.3-py3.7.egg.pip.operations',
			  'venv.lib.python3.7.site-packages.SystemConfiguration',
			  'venv.lib.python3.7.site-packages.LatentSemanticMapping',
			  'venv.lib.python3.7.site-packages.MultipeerConnectivity',
			  'venv.lib.python3.7.site-packages.VideoSubscriberAccount', 'socialbox', 'socialbox.routes',
			  'socialbox.helpers'],
	url='social-box.xyz',
	license='',
	author='joshhoughton',
	description=''
)
